## Building Predictive Model

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
raw_data_path = os.path.join(os.path.pardir, 'data', 'processed')
train_data_path = os.path.join(raw_data_path, 'train.csv')
test_data_path = os.path.join(raw_data_path, 'test.csv')

In [3]:
train_df = pd.read_csv(train_data_path,index_col='PassengerId')
test_df = pd.read_csv(test_data_path,index_col='PassengerId')

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
Family_Size           891 non-null int64
IsMother              891 non-null int64
isMale                891 non-null int64
Embarked_C            891 non-null int64
Embarked_Q            891 non-null int64
Embarked_S            891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-null int64
Title_Officer         891 non-null int64
Title_Sir             891 non-null int64
Age_State_Adults      891 non-null int64
Age_State_Child       891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-

In [5]:
X = train_df.loc[:, 'Age':].as_matrix().astype('float')
y = train_df['Survived'].ravel()
print(X.shape, y.shape)

(891, 32) (891,)


In [6]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(712, 32) (179, 32)
(712,) (179,)


In [7]:
# Calculating survival rate
print('mean survival in train: {0:.3f}'.format(np.mean(y_train)))
print('mean survival in test: {0:.3f}'.format(np.mean(y_test)))

mean survival in train: 0.383
mean survival in test: 0.385


In [8]:
import sklearn
sklearn.__version__

'0.19.1'

### Baseline Model

In [9]:
# Import package
from sklearn.dummy import DummyClassifier

In [10]:
# Create Dummy Model
model_dummy = DummyClassifier(strategy='most_frequent', random_state=0)


In [11]:
model_dummy.fit(X_train, y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [12]:
print('Score for baseline model: {0:.2f}'.format(model_dummy.score(X_test, y_test)))

Score for baseline model: 0.61


In [13]:
# Performance Metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [14]:
print('Accuracy Score for baseline model: {0:.2f}'.format(accuracy_score(y_test, model_dummy.predict(X_test))))

Accuracy Score for baseline model: 0.61


In [15]:
confusion_matrix(y_test, model_dummy.predict(X_test))

array([[110,   0],
       [ 69,   0]], dtype=int64)

In [16]:
print('Recall Score for baseline model: {0:.2f}'.format(recall_score(y_test, model_dummy.predict(X_test))))
print('Precision Score for baseline model: {0:.2f}'.format(precision_score(y_test, model_dummy.predict(X_test))))

Recall Score for baseline model: 0.00
Precision Score for baseline model: 0.00


F:\Arijit\Study\Technical\ML\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


### First Kaggle Submission

In [17]:
test_X = test_df.as_matrix().astype('float')
print(test_X)

[[34.5     7.8292  1.     ...  0.      0.      1.    ]
 [47.      7.      2.     ...  0.      0.      1.    ]
 [62.      9.6875  1.     ...  0.      1.      0.    ]
 ...
 [38.5     7.25    1.     ...  0.      0.      1.    ]
 [29.      8.05    1.     ...  0.      0.      1.    ]
 [ 4.     22.3583  3.     ...  0.      0.      1.    ]]


In [18]:
predictions = model_dummy.predict(test_X)
print (predictions)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]


In [19]:
df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived' : predictions})
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [20]:
submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
submission_file_path = os.path.join(submission_data_path, '01_summy.csv')
df_submission.to_csv(submission_file_path, index=False)

In [21]:
def get_submission_file(model, filename):
    test_X = test_df.as_matrix().astype('float')
    predictions = model.predict(test_X)
    
    df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived' : predictions})
    
    submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
    submission_file_path = os.path.join(submission_data_path, filename)
    df_submission.to_csv(submission_file_path, index=False)    

In [22]:
get_submission_file(model_dummy, '01_summy.csv')

### Logistic Regression Model

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
model_lr_1 = LogisticRegression(random_state=0)
model_lr_1.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [25]:
print('Score for Logistic Regression model: {0:.2f}'.format(model_lr_1.score(X_test, y_test)))

Score for Logistic Regression model: 0.83


In [26]:
print('Accuracy Score for Logistic Regression model: {0:.2f}'.format(accuracy_score(y_test, model_lr_1.predict(X_test))))
print('Confusion Matrix \n',confusion_matrix(y_test, model_lr_1.predict(X_test)))
print('Recall Score for Logistic Regression model: {0:.2f}'.format(recall_score(y_test, model_lr_1.predict(X_test))))
print('Precision Score for Logistic Regression model: {0:.2f}'.format(precision_score(y_test, model_lr_1.predict(X_test))))

Accuracy Score for Logistic Regression model: 0.83
Confusion Matrix 
 [[95 15]
 [15 54]]
Recall Score for Logistic Regression model: 0.78
Precision Score for Logistic Regression model: 0.78


In [27]:
model_lr_1.coef_

array([[-0.02823923,  0.00452545, -0.50041209,  0.61868136, -0.79957246,
         0.49081678,  0.46133822,  0.15184526,  0.27990235,  1.20395046,
         0.55924584, -1.46678373,  1.06442453, -0.22409278, -0.31264642,
         0.37276915,  0.73123111,  0.12285571, -0.16032125, -0.38782008,
         0.51920206,  1.09358418,  0.4034661 , -0.18461297, -0.30235349,
         0.16280266,  0.2447539 ,  0.28357968,  0.41286402,  0.96888856,
         0.47891632, -0.34380462]])

### Second Kaggle Submission

In [28]:
get_submission_file(model_lr_1, '02_lr.csv')

### Hyperparameter Optimization

In [29]:
model_lr_1 = LogisticRegression(random_state=0)

In [30]:
from sklearn.model_selection import GridSearchCV

In [31]:
parameters = {'C':[1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty' :['l1', 'l2']}
clf = GridSearchCV(model_lr_1, param_grid=parameters, cv=3)

In [32]:
clf.fit(X_train, y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [33]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [34]:
print('Best Score after HyperParameter Optimization: {0:.2f}'.format(clf.best_score_))

Best Score after HyperParameter Optimization: 0.83


In [35]:
print('Score after Logistic Regression Optimization: {0:.3f}'.format(clf.score(X_test, y_test)))

Score after Logistic Regression Optimization: 0.832


### 3rd Kaggle Submission

In [36]:
get_submission_file(clf, '03_lr.csv')

### Feature Normalization and Standardization

In [39]:
# MinMaxScaler -> Normalization, StandardScaler -> Standardization
from sklearn.preprocessing import MinMaxScaler, StandardScaler

#### Feature Normalization

In [47]:
scaler = MinMaxScaler()
#print(X_train)
X_train_scaled = scaler.fit_transform(X_train)
#print(X_train_scaled)

In [53]:
X_train_scaled[:, 1].min(), X_train_scaled[:, 1].max()

(0.0, 1.0)

In [55]:
X_test_scaled = scaler.fit_transform(X_test)

#### Feature Standardization

In [57]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

#### Create Model after Normalization and Standardization

In [58]:
parameters = {'C':[1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty' :['l1', 'l2']}
clf = GridSearchCV(model_lr_1, param_grid=parameters, cv=3)
clf.fit(X_train_scaled, y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [60]:
clf.best_score_

0.8146067415730337

In [64]:
print('Score after Logistic Regression - version 2: {0:.2f}'.format(clf.score(X_test_scaled, y_test)))

Score after Logistic Regression - version 2: 0.83


#### Model Persistence

In [75]:
# import pickle
import pickle

In [76]:
model_file_path = os.path.join(os.path.pardir, 'models', 'lr_model.pkl')
scaler_file_path = os.path.join(os.path.pardir, 'models', 'lr_scaler.pkl')

In [85]:
# persist model and scaler
model_file_pickle = open(model_file_path, 'wb')
scaler_file_pickle = open(scaler_file_path, 'wb')

In [86]:
pickle.dump(clf, model_file_pickle)
pickle.dump(scaler, scaler_file_pickle)

In [87]:
model_file_pickle.close()
scaler_file_pickle.close()

#### Load persisted File

In [92]:
model_file_pickle = open(model_file_path, 'r')
scaler_file_pickle = open(scaler_file_path, 'r')

print(model_file_pickle)
print(scaler_file_pickle)

#clf_loaded = pickle.load(model_file_pickle)
#scaler_loaded = pickle.load(scaler_file_pickle)

model_file_pickle.close()
scaler_file_pickle.close()

<_io.TextIOWrapper name='..\\models\\lr_model.pkl' mode='r' encoding='cp1252'>
<_io.TextIOWrapper name='..\\models\\lr_scaler.pkl' mode='r' encoding='cp1252'>


### Machine Learning API using Flask

#### Building API

In [89]:
hello_world_script_file = os.path.join(os.path.pardir, 'src', 'models', 'machine_learning_api.py')

In [110]:
%%writefile $hello_world_script_file
from flask import Flask, request
import pandas as pd
import numpy as np
import os, json, requests, pickle

app = Flask(__name__)


directry_path = os.path.join(os.path.pardir, os.path.pardir)
model_file_path = os.path.join(directry_path, 'models', 'lr_model.pkl')
scaler_file_path = os.path.join(directry_path, 'models', 'lr_scaler.pkl')

print(model_file_path)

model = pickle.load(open(model_file_path))
scaler = pickle.load(open(scaler_file_path))

columns = [
    u'Age', u'Fare', u'Family_Size', u'IsMother', u'isMale', u'Embarked_C', u'Embarked_Q', \
    u'Embarked_S', u'Title_Lady', u'Title_Master', u'Title_Miss', u'Title_Mr', u'Title_Mrs', u'Title_Officer', \
    u'Title_Sir', u'Age_State_Adults', u'Age_State_Child', u'Deck_A', u'Deck_B', u'Deck_C', u'Deck_D', u'Deck_E', \
    u'Deck_F', u'Deck_G', u'Deck_Z', u'Fare_Bin_very low', u'Fare_Bin_low', u'Fare_Bin_high', u'Fare_Bin_very high', \
    u'Pclass_1', u'Pclass_2', u'Pclass_3'
]

@app.route('/api', methods=['POST'])

def make_predictions():
    #Read Data from request
    data = request.get_json(force=True)
    #Make data frame.
    df = pd.read_json(data)
    # Extract Passenger IDs
    passenger_ids = df['PassengerID'].ravel()
    # Get Actuals from inpiut frame
    actuals = df['Survived'].ravel()
    # Convert dataframe into Matrix format in float
    X = df[columns].as_matrix().astype('float')
    # Scaling Data Set
    x_scaled = scaler.transform(X)
    # Make predictions
    predictions = model.predict(x_scaled)
    # Make response data frame
    df_response = pd.DataFrame({'PassengerID' : passenger_ids, 'Predicted': predictions, 'Actual' : actuals})
    # return response after converting to json
    return df_response.to_json()

if __name__ == '__main__':
    app.run(port=10001, debug=True)
    

Overwriting ..\src\models\machine_learning_api.py
