## Building Predictive Model

In [1]:
import pandas as pd
import numpy as np
import os

In [8]:
raw_data_path = os.path.join(os.path.pardir, 'data', 'processed')
train_data_path = os.path.join(raw_data_path, 'train.csv')
test_data_path = os.path.join(raw_data_path, 'test.csv')

In [9]:
train_df = pd.read_csv(train_data_path,index_col='PassengerId')
test_df = pd.read_csv(test_data_path,index_col='PassengerId')

In [12]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
Family_Size           891 non-null int64
IsMother              891 non-null int64
isMale                891 non-null int64
Embarked_C            891 non-null int64
Embarked_Q            891 non-null int64
Embarked_S            891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-null int64
Title_Officer         891 non-null int64
Title_Sir             891 non-null int64
Age_State_Adults      891 non-null int64
Age_State_Child       891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-

In [26]:
X = train_df.loc[:, 'Age':].as_matrix().astype('float')
y = train_df['Survived'].ravel()
print(X.shape, y.shape)

(891, 32) (891,)


In [30]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(712, 32) (179, 32)
(712,) (179,)


In [60]:
# Calculating survival rate
print('mean survival in train: {0:.3f}'.format(np.mean(y_train)))
print('mean survival in test: {0:.3f}'.format(np.mean(y_test)))

mean survival in train: 0.383
mean survival in test: 0.385


In [65]:
import sklearn
sklearn.__version__

'0.19.1'

### Baseline Model

In [67]:
# Import package
from sklearn.dummy import DummyClassifier

In [72]:
# Create Dummy Model
model_dummy = DummyClassifier(strategy='most_frequent', random_state=0)


In [76]:
model_dummy.fit(X_train, y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [80]:
print('Score for baseline model: {0:.2f}'.format(model_dummy.score(X_test, y_test)))

Score for baseline model: 0.61


In [83]:
# Performance Metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [86]:
print('Accuracy Score for baseline model: {0:.2f}'.format(accuracy_score(y_test, model_dummy.predict(X_test))))

Accuracy Score for baseline model: 0.61


In [91]:
confusion_matrix(y_test, model_dummy.predict(X_test))

array([[110,   0],
       [ 69,   0]], dtype=int64)

In [93]:
print('Recall Score for baseline model: {0:.2f}'.format(recall_score(y_test, model_dummy.predict(X_test))))
print('Precision Score for baseline model: {0:.2f}'.format(precision_score(y_test, model_dummy.predict(X_test))))

Recall Score for baseline model: 0.00
Precision Score for baseline model: 0.00


F:\Arijit\Study\Technical\ML\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


### First Kaggle Submission

In [100]:
test_X = test_df.as_matrix().astype('float')
print(test_X)

[[34.5     7.8292  1.     ...  0.      0.      1.    ]
 [47.      7.      2.     ...  0.      0.      1.    ]
 [62.      9.6875  1.     ...  0.      1.      0.    ]
 ...
 [38.5     7.25    1.     ...  0.      0.      1.    ]
 [29.      8.05    1.     ...  0.      0.      1.    ]
 [ 4.     22.3583  3.     ...  0.      0.      1.    ]]


In [103]:
predictions = model_dummy.predict(test_X)
print (predictions)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]


In [107]:
df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived' : predictions})
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [112]:
submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
submission_file_path = os.path.join(submission_data_path, '01_summy.csv')
df_submission.to_csv(submission_file_path, index=False)

In [116]:
def get_submission_file(model, filename):
    test_X = test_df.as_matrix().astype('float')
    predictions = model.predict(test_X)
    
    df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived' : predictions})
    
    submission_data_path = os.path.join(os.path.pardir, 'data', 'external')
    submission_file_path = os.path.join(submission_data_path, filename)
    df_submission.to_csv(submission_file_path, index=False)    

In [118]:
get_submission_file(model_dummy, '01_summy.csv')

### Logistic Regression Model

In [130]:
from sklearn.linear_model import LogisticRegression

In [131]:
model_lr_1 = LogisticRegression(random_state=0)
model_lr_1.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [132]:
print('Score for Logistic Regression model: {0:.2f}'.format(model_lr_1.score(X_test, y_test)))

Score for Logistic Regression model: 0.83


In [134]:
print('Accuracy Score for Logistic Regression model: {0:.2f}'.format(accuracy_score(y_test, model_lr_1.predict(X_test))))
print('Confusion Matrix \n',confusion_matrix(y_test, model_lr_1.predict(X_test)))
print('Recall Score for Logistic Regression model: {0:.2f}'.format(recall_score(y_test, model_lr_1.predict(X_test))))
print('Precision Score for Logistic Regression model: {0:.2f}'.format(precision_score(y_test, model_lr_1.predict(X_test))))

Accuracy Score for Logistic Regression model: 0.83
Confusion Matrix 
 [[95 15]
 [15 54]]
Recall Score for Logistic Regression model: 0.78
Precision Score for Logistic Regression model: 0.78


In [136]:
model_lr_1.coef_

array([[-0.02823923,  0.00452545, -0.50041209,  0.61868136, -0.79957246,
         0.49081678,  0.46133822,  0.15184526,  0.27990235,  1.20395046,
         0.55924584, -1.46678373,  1.06442453, -0.22409278, -0.31264642,
         0.37276915,  0.73123111,  0.12285571, -0.16032125, -0.38782008,
         0.51920206,  1.09358418,  0.4034661 , -0.18461297, -0.30235349,
         0.16280266,  0.2447539 ,  0.28357968,  0.41286402,  0.96888856,
         0.47891632, -0.34380462]])

### Second Kaggle Submission

In [137]:
get_submission_file(model_lr_1, '02_lr.csv')